
title: kk-job

address: :8088
prefix: /kk-job/

token: UTFVBNMKOIOK__IUH
tableCount: 128

db:
  title: 写数据库
  name: mysql
  url: root:123456@tcp(127.0.0.1:3306)/kk?charset=utf8mb4&allowNativePasswords=true
  prefix: job_
  maxIdleConns: 1
  maxOpenConns: 6

dbr:
  title: 读数据库
  name: mysql
  url: root:123456@tcp(127.0.0.1:3306)/kk?charset=utf8mb4&allowNativePasswords=true
  prefix: job_
  maxIdleConns: 6
  maxOpenConns: 20

